config/routes.rb
Rails.application.routes.draw do
  root "sites#index"

  resources :articles, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  scope :available , -> { where("status = 'A'") }
  scope :unavailable , -> { where("status = 'D'") }

  def to_param
    self.slug
  end
end

app/models/site.rb
class Site < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find_by_slug(params[:id])
    raise "We cannot find the article you're looking for" unless !!@article
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  layout "site"
  def index
    @site = Site.find_by_slug("portfolio")
    @articles = Article.available
    raise "We cannot find the site you're looking for" unless !!@site
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript_exists_base_controller?(script)
    script = "#{Rails.root}/app/assets/javascripts/#{params[:controller]}.js"
    File.exists?(script) || File.exists?("#{script}.coffee")
  end

  def stylesheet_exists_base_controller?(sheet)
    sheet = "#{Rails.root}/app/assets/stylesheets/#{params[:controller]}.css"
    if File.exists?(sheet)
      sheet
    elsif File.exists?("#{sheet}.scss")
      "#{sheet}.scss"
    else
      "#{sheet}.sass"
    end
  end

  def javascript_exists_base_slug?(script)
    script = "#{Rails.root}/app/assets/javascripts/#{script}.js"
    File.exists?(script) || File.exists?("#{script}.coffee")
  end

  def stylesheet_exists_base_slug?(sheet)
    sheet = "#{Rails.root}/app/assets/stylesheets/#{sheet}.css"
    if File.exists?(sheet)
      sheet
    elsif File.exists?("#{sheet}.scss")
      "#{sheet}.scss"
    elsif File.exists?("#{sheet}.sass")
      "#{sheet}.sass"
    else
      "#{sheet}.sass"
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/articles/available/_my-not-so-random-thoughts.html.erb
<h1><%= @article.name%></h1>

app/views/articles/available/_today-toughts.html.erb
<h1><%= @article.name%></h1>

app/views/articles/show.html.erb
<%= render partial: "articles/available/#{@article.slug}" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <title>Denise Meagher | Web Developer &amp; Designer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Questrial|Raleway:300,400" rel="stylesheet">
    <!--materialize icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--font awesome-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

    <% if stylesheet_exists_base_slug?(params[:id]) %>
      <%= stylesheet_link_tag params[:id] %>
    <% else %>
      <%= stylesheet_link_tag "site" %>
    <% end %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

  </head>

  <body>
      <%= yield %>
      <div class="javascript">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
        <% if javascript_exists_base_slug?(params[:id]) %>
          <%= javascript_include_tag params[:id] %>
        <% end %>
      </div>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <title>Denise Meagher | Web Developer &amp; Designer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Questrial|Raleway:300,400" rel="stylesheet">
    <!--materialize icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--font awesome-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <% if stylesheet_exists_base_slug?(@site.slug) %>
      <%= stylesheet_link_tag @site.slug%>
    <% else %>
      <%= stylesheet_link_tag "site" %>
    <% end %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

  </head>

  <body>
      <%= yield %>

      <div class="javascript">
        <% if javascript_exists_base_slug?(@site.slug) %>
          <%= javascript_include_tag @site.slug %>
        <% end %>
      </div>
  </body>
</html>

app/views/sites/index.html.erb
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="#Intro" class="brand-logo teal-text">dsm</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <!-- <li class="nav-font"><a href="About.html">About</a></li> -->
          <li class="nav-font"><a href="#Projects">Projects</a></li>
          <li class="nav-font"><a href="#Contact">Contact</a></li>
        </ul>

        <ul class="side-nav" id="mobile-demo">
        <li><a href="#" class="x">X</a></li>
          <!-- <li class="smoothScroll"><a href="#Intro">About</a></li> -->
          <li><a href="#Projects">Projects</a></li>
          <li><a href="#Contact">Contact</a></li>
        </ul>
      </div> <!-- /nav-wrapper -->
    </nav>
  </div> <!-- /navbar fixed -->

<!-- Intro -->
  <div class="scrollspy valign-wrapper" id="Intro">
    <div class="row">
      <div class="col s12 m8 offset-m2 valign">
        <center><h1 class="site-intro"> Designer // Developer
          <br> Creative at heart. Passionate about ideas and design.
          This is just a taste.
        </h1></center>
      </div>
    </div>
  </div><!-- /intro -->

  <div id="Quote-container">

    <div class="container">
      <div class="row random-quotes">
        <i class="col m1 medium material-icons i-left">format_quote</i>
        <div class="col m10">
          <h3 class="quote"> Designers are crazy and yet sane enough to know where to draw the line. </h3>
          <h5 class="quote-author"> &mdash; Benjamin Valbret </h5>
        </div>
          <i class="col m1 medium material-icons i-right">format_quote</i>
      </div>
    </div>
  </div>



<div>
  <%@articles.each do |article|%>
    <h1> <%= link_to article.name, article_path(article)%></h1>
  <% end -%>
</div>

  <!-- <div class="divider"></div> -->

<!-- Projects -->
  <div class="container">
    <div class="scrollspy" id="Projects">
      <center><h4> Web sites/apps </h4></center>

      <div class="row projects-carousel">
        <!-- project 1 -->
        <div class="col s12 examples">
          <h5> Design Mockup </h5>
          <div class="col s12 m6 offset-m3">
            <p> Showcasing ability to take an image (design mockup in form of a jpg. psd, pdf etc. ) and recreating it for use on the web. </p>
            <a class="btn waves-effect" href="http://design-mockup.surge.sh/" target="blank">View Mockup </a>
          </div>
          <img class="hoverable responsive-img" src="https://s3.amazonaws.com/denisemeagher/portfolio1/design_mockup.jpg" alt="Design Mockup">
        </div>

        <!-- project 2 -->
        <div class="col s12 examples">
          <h5> TOM. </h5>
          <div class="col s12 m6 offset-m3">
            <p> TOM is a subscription plan for monthly delivery of a customized box of feminine hygiene products. </p>
            <a class="btn waves-effect" href="http://tom-box.herokuapp.com/login" target="blank">Visit TOM </a>
          </div>
          <img class="hoverable responsive-img" src="https://s3.amazonaws.com/denisemeagher/portfolio1/tom.jpg" alt="Tom homepage">
        </div>

        <!--project 3 -->
        <div class="col s12 examples">
          <h5> Moonlighter Maker Space </h5>
          <div class="col s12 m6 offset-m3">
            <p> Moonlighter is a venue for creative collaboration and a community of innovators mixing digital technologies with physical objects. </p>
            <a class="btn" href="http://moonlighter.co/" target="blank">Visit Moonlighter </a>
          </div>
          <img class="hoverable responsive-img" src="https://s3.amazonaws.com/denisemeagher/portfolio1/moonlighter.jpg" alt="Moonlighter Makerspace homepage">
        </div>
      </div>
    </div>
  </div>

  <!-- /projects -->
  <div class="divider"></div>

  <!-- Design -->
  <div class="container">
    <div id="Designs">
      <center><h4> Design print/digital </h4></center>

      <!-- design row 1 -->
      <div class="row">
        <div class="col s12 l3 designs">
          <h5> Bradford White Water Heaters</h5>
          <p>Water Heater quick tips for maintenance workers. <br> Include all relevant information in a visually appealing way and incorporate Bradford White styles while adhering to the HD Supply brand style guidelines.</p>
        </div>
        <div class="col s12 m4 l3 designs">
          <img class="responsive-img materialboxed" src="https://s3.amazonaws.com/denisemeagher/portfolio1/bradford_poster_electric.png" alt="Bradford White Electric Water Heater info poster">
        </div>
        <div class="col s12 m4 l3 designs">
          <img class="responsive-img materialboxed" src="https://s3.amazonaws.com/denisemeagher/portfolio1/bradford_poster_gas.png" alt="Bradford White Gas Water Heater info poster">
        </div>
        <div class="col s12 m4 l3 designs">
          <img class="responsive-img materialboxed" src="https://s3.amazonaws.com/denisemeagher/portfolio1/bradford_flyer.png" alt="Bradford White Water Heater information pamphlet">
        </div>
      </div><!-- design row 1 -->

      <hr>
      <!-- design row 2 -->
      <div class="row">
        <div class="col s12 m4 designs">
          <h5> Special Order Plumbing &amp; Hardware Guide </h5>
          <p> Opportunity to apply new layout and typography treatment from what was typically done, while staying true to HD Supply brand style guidelines. </p>
        </div>
        <div class="col s12 m4 designs">
          <img class="responsive-img hoverable materialboxed" data-caption="Front and Back Covers" src="https://s3.amazonaws.com/denisemeagher/portfolio1/SO_guide_covers.png" alt="Special Order Plumbing and Hardware Guide Covers">
        </div>
        <div class="col s12 m4 designs">
          <img class="responsive-img materialboxed hoverable" data-caption="Table of contents and example spreads from each category" src="https://s3.amazonaws.com/denisemeagher/portfolio1/SO_guide_content.png" alt="Special Order Plumbing and Hardware Guide Content Examples">
        </div>
      </div><!-- /design row 2 -->

      <hr>
      <!-- design row 3 -->
      <div class="row">
        <div class="col s12 m3 designs">
          <h5> HD Supply Spring Carnival</h5>
          <p> Employee Spring Carnival annoucement poster, welcome poster and game/booth signs. </p>
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img hoverable materialboxed" data-caption="Spring Carnival Announcement" src="https://s3.amazonaws.com/denisemeagher/portfolio1/spring_festival1.png">
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img materialboxed hoverable" data-caption="Spring Carnival Welcome Sign" src="https://s3.amazonaws.com/denisemeagher/portfolio1/spring_festival2.png">
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img materialboxed hoverable" data-caption="Spring Carnival Booth Signs" src="https://s3.amazonaws.com/denisemeagher/portfolio1/spring_festival3.png">
        </div>
      </div><!-- /design row 3 -->
      <hr>
      <!-- design row 4 -->
      <div class="row">
        <div class="col s12 m3 designs">
          <h5>TAA (Texas Apartment Association) Tradeshow Collateral</h5>
          <p> Worked with one additonal designer to design logo and all accompanying collateral pieces incorporating current years tradeshow theme. </p>
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img hoverable materialboxed" data-caption="2013 TAA Tradeshow logo" src="https://s3.amazonaws.com/denisemeagher/portfolio1/TAA_logo.png" alt="2013 TAA logo">
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img materialboxed hoverable" data-caption="2013 TAA Tradeshow tabletop signs" src="https://s3.amazonaws.com/denisemeagher/portfolio1/TAA_tabletop_signs.png" alt="2013 TAA Tradeshow tabletop signs">
        </div>
        <div class="col s12 m3 designs">
          <img class="responsive-img materialboxed hoverable" data-caption="2013 TAA Tradeshow preshow postcard" src="https://s3.amazonaws.com/denisemeagher/portfolio1/TAA_postcards.png" alt="2013 TAA Tradeshow preshow postcards">
        </div>
      </div><!-- /design row 4 -->

    </div><!-- /Designs -->
  </div><!-- /container -->
  <!-- /Design -->

  <div class="divider"></div>

  <!-- footer -->
  <footer>
    <div class="scrollspy" id="Contact">
      <div class="container">
      <center>
        <div class="row">
          <div class="col s12">
            <h6><i class="fa fa-hand-peace-o teal-text"> </i>&nbsp; Let's Connect</h6>
          </div>
          <div class="col s12">
            <ul>
              <li><a href="https://www.linkedin.com/in/denisemeagher" target="_blank"><i class="fa fa-linkedin-square linkedin" placeholder="linkedin"></i></a></li>
              <li><a href="https://github.com/denisemeagher" target="_blank"><i class="fa fa-github-square git"></i></a></li>
              <li><a href="https://twitter.com/denisemeagher" target="_blank"><i class="fa fa-twitter-square twitter"></i></a></li>
              <li><a href="https://www.instagram.com/dizzm/" target="_blank" alt="Instagram"><i class="fa fa-instagram instagram"></i></a></li>
              <li><a class="email" href="mailto:hello@denisemeagher.co" alt ="email me at hello@denisemeagher.co">
                  <i class="fa fa-envelope-o"></i></a></li>
                  <!-- <li><a href="tel:707-315-0319"><i class="fa fa-phone-square fa-3x phone" aria-hidden="true"></i></a></li> -->
                </ul>
          </div>
        </div><!--/row -->
        <div class="col s12">
          <a href="http://denisemeagher.co/">Copyright © Denise S. Meagher 2017</a>
          <p><i class="material-icons">favorite</i> • <i class="material-icons">sentiment_very_satisfied</i> • <i class="material-icons">filter_vintage</i> • <i class="material-icons">music_note</i> • <i class="material-icons">star</i></p>
        </div>
      </center>
      </div><!-- container -->
    </div><!-- /Contact -->
  </footer>
  <div class="color-block">
</div>